from enum import Enum

class ArticulationMethod(Enum):
    PLOSIVE_PLAIN = 0
    PLOSIVE_PLAIN_CONSONANTS = ('ㅂ', 'ㄷ', 'ㄱ')
    PLOSIVE_TENSE = 1
    PLOSIVE_TENSE_CONSONANTS = ('ㅃ', 'ㄸ', 'ㄲ')
    PLOSIVE_ASPIRATED = 2
    PLOSIVE_ASPIRATED_CONSONANTS = ('ㅍ', 'ㅌ', 'ㅋ')
    AFFRICATE_PLAIN = 3
    AFFRICATE_PLAIN_CONSONANTS = ('ㅈ')
    AFFRICATE_TENSE = 4
    AFFRICATE_TENSE_CONSONANTS = ('ㅉ')
    AFFRICATE_ASPIRATED = 5
    AFFRICATE_ASPIRATED_CONSONANTS = ('ㅊ')
    FRICATIVE_PLAIN = 6
    FRICATIVE_PLAIN_CONSONANTS = ('ㅅ', 'ㅎ')
    FRICATIVE_TENSE = 7
    FRICATIVE_TENSE_CONSONANTS = ('ㅆ')
    NASAL = 8
    NASAL_CONSONANTS = ('ㅁ', 'ㄴ', 'ㅇ')
    LIQUID = 9
    LIQUID_CONSONANTS = ('ㄹ')
    INVALID_LETTER = 10
